### ISSUE TITLE
图片自适应布局

### ISSUE THREAD

**Issue by jayxiangnan** [jayxiangnan/Notes#1]
# 图片自适应布局

标签： css 布局

---

图片自适应布局主要为了解决以下几个问题：

+ 图片能够随屏幕的宽度变化而变化
+ 图片加载之前不会出现图片塌陷

talk is cheap , show code  >!<

1、html部分
```html
<ul class="wrap">
    <li class="item">
        <div class="img-box">
            <img src="">
        </div>
    </li>
    <li class="item">
        <div class="img-box">
            <img src="">
        </div>
    </li>
    <li class="item">
        <div class="img-box">
            <img src="">
        </div>
    </li>
    <li class="item">
        <div class="img-box">
            <img src="">
        </div>
    </li>
</ul>
```

2、css部分
```css
.wrap{
    min-width: 1000px;
    margin: 0 auto;
    font-size: 0;
}
.item{
    display: inline-block;
    width: calc(25% - 10px);
    margin: 10px 5px 0;
    vertical-align: top;
}
.img-box{
    position: relative;
    padding-top: 100%;
    background: #f0f0f0;
}
.img-box img{
    position: absolute;
    top: 0;
    left: 0;
    display: block;
    width: 100%;
    height: 100%;
}
```
